name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.18.0'

      - name: Enable the package-manager version from package.json
        run: |
          corepack enable
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate prisma client
        run: pnpm run prisma:generate

      - name: Run ESLint
        run: pnpm run lint

      - name: Run Type Checking
        run: pnpm run typecheck
